/*
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * The version of the OpenAPI document: 3.1.7
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.FeeApplicableRangeProperty;
import com.konfigthis.client.model.FeeChargeCapPropertyInner;
import com.konfigthis.client.model.OtherApplicationFrequencyProperty1;
import com.konfigthis.client.model.OtherCalculationFrequencyProperty1;
import com.konfigthis.client.model.OtherFeeCategoryTypeProperty;
import com.konfigthis.client.model.OtherFeeRateTypeProperty;
import com.konfigthis.client.model.OtherFeeTypeProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for FeeChargeDetailPropertyInner
 */
public class FeeChargeDetailPropertyInnerTest {
    private final FeeChargeDetailPropertyInner model = new FeeChargeDetailPropertyInner();

    /**
     * Model tests for FeeChargeDetailPropertyInner
     */
    @Test
    public void testFeeChargeDetailPropertyInner() {
        // TODO: test FeeChargeDetailPropertyInner
    }

    /**
     * Test the property 'applicationFrequency'
     */
    @Test
    public void applicationFrequencyTest() {
        // TODO: test applicationFrequency
    }

    /**
     * Test the property 'calculationFrequency'
     */
    @Test
    public void calculationFrequencyTest() {
        // TODO: test calculationFrequency
    }

    /**
     * Test the property 'feeAmount'
     */
    @Test
    public void feeAmountTest() {
        // TODO: test feeAmount
    }

    /**
     * Test the property 'feeApplicableRange'
     */
    @Test
    public void feeApplicableRangeTest() {
        // TODO: test feeApplicableRange
    }

    /**
     * Test the property 'feeCategory'
     */
    @Test
    public void feeCategoryTest() {
        // TODO: test feeCategory
    }

    /**
     * Test the property 'feeChargeCap'
     */
    @Test
    public void feeChargeCapTest() {
        // TODO: test feeChargeCap
    }

    /**
     * Test the property 'feeRate'
     */
    @Test
    public void feeRateTest() {
        // TODO: test feeRate
    }

    /**
     * Test the property 'feeRateType'
     */
    @Test
    public void feeRateTypeTest() {
        // TODO: test feeRateType
    }

    /**
     * Test the property 'feeType'
     */
    @Test
    public void feeTypeTest() {
        // TODO: test feeType
    }

    /**
     * Test the property 'negotiableIndicator'
     */
    @Test
    public void negotiableIndicatorTest() {
        // TODO: test negotiableIndicator
    }

    /**
     * Test the property 'notes'
     */
    @Test
    public void notesTest() {
        // TODO: test notes
    }

    /**
     * Test the property 'otherApplicationFrequency'
     */
    @Test
    public void otherApplicationFrequencyTest() {
        // TODO: test otherApplicationFrequency
    }

    /**
     * Test the property 'otherCalculationFrequency'
     */
    @Test
    public void otherCalculationFrequencyTest() {
        // TODO: test otherCalculationFrequency
    }

    /**
     * Test the property 'otherFeeCategoryType'
     */
    @Test
    public void otherFeeCategoryTypeTest() {
        // TODO: test otherFeeCategoryType
    }

    /**
     * Test the property 'otherFeeRateType'
     */
    @Test
    public void otherFeeRateTypeTest() {
        // TODO: test otherFeeRateType
    }

    /**
     * Test the property 'otherFeeType'
     */
    @Test
    public void otherFeeTypeTest() {
        // TODO: test otherFeeType
    }

}
