/*
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * The version of the OpenAPI document: 3.1.7
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OBActiveOrHistoricCurrencyAndAmount5
 */
public class OBActiveOrHistoricCurrencyAndAmount5Test {
    private final OBActiveOrHistoricCurrencyAndAmount5 model = new OBActiveOrHistoricCurrencyAndAmount5();

    /**
     * Model tests for OBActiveOrHistoricCurrencyAndAmount5
     */
    @Test
    public void testOBActiveOrHistoricCurrencyAndAmount5() {
        // TODO: test OBActiveOrHistoricCurrencyAndAmount5
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

}
