/*
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * The version of the OpenAPI document: 3.1.7
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.OBAccountStatus1Code;
import com.konfigthis.client.model.OBExternalAccountSubType1Code;
import com.konfigthis.client.model.OBExternalAccountType1Code;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OBAccount6Basic
 */
public class OBAccount6BasicTest {
    private final OBAccount6Basic model = new OBAccount6Basic();

    /**
     * Model tests for OBAccount6Basic
     */
    @Test
    public void testOBAccount6Basic() {
        // TODO: test OBAccount6Basic
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    public void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'accountSubType'
     */
    @Test
    public void accountSubTypeTest() {
        // TODO: test accountSubType
    }

    /**
     * Test the property 'accountType'
     */
    @Test
    public void accountTypeTest() {
        // TODO: test accountType
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'maturityDate'
     */
    @Test
    public void maturityDateTest() {
        // TODO: test maturityDate
    }

    /**
     * Test the property 'nickname'
     */
    @Test
    public void nicknameTest() {
        // TODO: test nickname
    }

    /**
     * Test the property 'openingDate'
     */
    @Test
    public void openingDateTest() {
        // TODO: test openingDate
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'statusUpdateDateTime'
     */
    @Test
    public void statusUpdateDateTimeTest() {
        // TODO: test statusUpdateDateTime
    }

    /**
     * Test the property 'switchStatus'
     */
    @Test
    public void switchStatusTest() {
        // TODO: test switchStatus
    }

}
