/*
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * The version of the OpenAPI document: 3.1.7
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OBCashAccount61
 */
public class OBCashAccount61Test {
    private final OBCashAccount61 model = new OBCashAccount61();

    /**
     * Model tests for OBCashAccount61
     */
    @Test
    public void testOBCashAccount61() {
        // TODO: test OBCashAccount61
    }

    /**
     * Test the property 'identification'
     */
    @Test
    public void identificationTest() {
        // TODO: test identification
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'schemeName'
     */
    @Test
    public void schemeNameTest() {
        // TODO: test schemeName
    }

    /**
     * Test the property 'secondaryIdentification'
     */
    @Test
    public void secondaryIdentificationTest() {
        // TODO: test secondaryIdentification
    }

}
