/*
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * The version of the OpenAPI document: 3.1.7
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OBCreditDebitCode2
 */
public class OBCreditDebitCode2Test {
    /**
     * Model tests for OBCreditDebitCode2
     */
    @Test
    public void testOBCreditDebitCode2() {
        // TODO: test OBCreditDebitCode2
    }

}
