/*
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * The version of the OpenAPI document: 3.1.7
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.OBReadDirectDebit2DataDirectDebitInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OBReadDirectDebit2Data
 */
public class OBReadDirectDebit2DataTest {
    private final OBReadDirectDebit2Data model = new OBReadDirectDebit2Data();

    /**
     * Model tests for OBReadDirectDebit2Data
     */
    @Test
    public void testOBReadDirectDebit2Data() {
        // TODO: test OBReadDirectDebit2Data
    }

    /**
     * Test the property 'directDebit'
     */
    @Test
    public void directDebitTest() {
        // TODO: test directDebit
    }

}
