/*
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * The version of the OpenAPI document: 3.1.7
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.OBOtherCodeType10;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OBReadProduct2DataProductInnerOtherProductTypeProductDetails
 */
public class OBReadProduct2DataProductInnerOtherProductTypeProductDetailsTest {
    private final OBReadProduct2DataProductInnerOtherProductTypeProductDetails model = new OBReadProduct2DataProductInnerOtherProductTypeProductDetails();

    /**
     * Model tests for OBReadProduct2DataProductInnerOtherProductTypeProductDetails
     */
    @Test
    public void testOBReadProduct2DataProductInnerOtherProductTypeProductDetails() {
        // TODO: test OBReadProduct2DataProductInnerOtherProductTypeProductDetails
    }

    /**
     * Test the property 'feeFreeLength'
     */
    @Test
    public void feeFreeLengthTest() {
        // TODO: test feeFreeLength
    }

    /**
     * Test the property 'feeFreeLengthPeriod'
     */
    @Test
    public void feeFreeLengthPeriodTest() {
        // TODO: test feeFreeLengthPeriod
    }

    /**
     * Test the property 'monthlyMaximumCharge'
     */
    @Test
    public void monthlyMaximumChargeTest() {
        // TODO: test monthlyMaximumCharge
    }

    /**
     * Test the property 'notes'
     */
    @Test
    public void notesTest() {
        // TODO: test notes
    }

    /**
     * Test the property 'otherSegment'
     */
    @Test
    public void otherSegmentTest() {
        // TODO: test otherSegment
    }

    /**
     * Test the property 'segment'
     */
    @Test
    public void segmentTest() {
        // TODO: test segment
    }

}
