/*
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * The version of the OpenAPI document: 3.1.7
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.OBActiveOrHistoricCurrencyAndAmount1;
import com.konfigthis.client.model.OBExternalScheduleType1Code;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OBScheduledPayment3Basic
 */
public class OBScheduledPayment3BasicTest {
    private final OBScheduledPayment3Basic model = new OBScheduledPayment3Basic();

    /**
     * Model tests for OBScheduledPayment3Basic
     */
    @Test
    public void testOBScheduledPayment3Basic() {
        // TODO: test OBScheduledPayment3Basic
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    public void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'debtorReference'
     */
    @Test
    public void debtorReferenceTest() {
        // TODO: test debtorReference
    }

    /**
     * Test the property 'instructedAmount'
     */
    @Test
    public void instructedAmountTest() {
        // TODO: test instructedAmount
    }

    /**
     * Test the property 'reference'
     */
    @Test
    public void referenceTest() {
        // TODO: test reference
    }

    /**
     * Test the property 'scheduledPaymentDateTime'
     */
    @Test
    public void scheduledPaymentDateTimeTest() {
        // TODO: test scheduledPaymentDateTime
    }

    /**
     * Test the property 'scheduledPaymentId'
     */
    @Test
    public void scheduledPaymentIdTest() {
        // TODO: test scheduledPaymentId
    }

    /**
     * Test the property 'scheduledType'
     */
    @Test
    public void scheduledTypeTest() {
        // TODO: test scheduledType
    }

}
