/*
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * The version of the OpenAPI document: 3.1.7
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.OBActiveOrHistoricCurrencyAndAmount10;
import com.konfigthis.client.model.OBActiveOrHistoricCurrencyAndAmount9;
import com.konfigthis.client.model.OBBankTransactionCodeStructure1;
import com.konfigthis.client.model.OBBranchAndFinancialInstitutionIdentification61;
import com.konfigthis.client.model.OBBranchAndFinancialInstitutionIdentification62;
import com.konfigthis.client.model.OBCashAccount60;
import com.konfigthis.client.model.OBCashAccount61;
import com.konfigthis.client.model.OBCreditDebitCode1;
import com.konfigthis.client.model.OBCurrencyExchange5;
import com.konfigthis.client.model.OBEntryStatus1Code;
import com.konfigthis.client.model.OBMerchantDetails1;
import com.konfigthis.client.model.OBTransactionCardInstrument1;
import com.konfigthis.client.model.OBTransactionCashBalance;
import com.konfigthis.client.model.OBTransactionMutability1Code;
import com.konfigthis.client.model.ProprietaryBankTransactionCodeStructure1;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OBTransaction6
 */
public class OBTransaction6Test {
    private final OBTransaction6 model = new OBTransaction6();

    /**
     * Model tests for OBTransaction6
     */
    @Test
    public void testOBTransaction6() {
        // TODO: test OBTransaction6
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    public void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'addressLine'
     */
    @Test
    public void addressLineTest() {
        // TODO: test addressLine
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'balance'
     */
    @Test
    public void balanceTest() {
        // TODO: test balance
    }

    /**
     * Test the property 'bankTransactionCode'
     */
    @Test
    public void bankTransactionCodeTest() {
        // TODO: test bankTransactionCode
    }

    /**
     * Test the property 'bookingDateTime'
     */
    @Test
    public void bookingDateTimeTest() {
        // TODO: test bookingDateTime
    }

    /**
     * Test the property 'cardInstrument'
     */
    @Test
    public void cardInstrumentTest() {
        // TODO: test cardInstrument
    }

    /**
     * Test the property 'chargeAmount'
     */
    @Test
    public void chargeAmountTest() {
        // TODO: test chargeAmount
    }

    /**
     * Test the property 'creditDebitIndicator'
     */
    @Test
    public void creditDebitIndicatorTest() {
        // TODO: test creditDebitIndicator
    }

    /**
     * Test the property 'creditorAccount'
     */
    @Test
    public void creditorAccountTest() {
        // TODO: test creditorAccount
    }

    /**
     * Test the property 'creditorAgent'
     */
    @Test
    public void creditorAgentTest() {
        // TODO: test creditorAgent
    }

    /**
     * Test the property 'currencyExchange'
     */
    @Test
    public void currencyExchangeTest() {
        // TODO: test currencyExchange
    }

    /**
     * Test the property 'debtorAccount'
     */
    @Test
    public void debtorAccountTest() {
        // TODO: test debtorAccount
    }

    /**
     * Test the property 'debtorAgent'
     */
    @Test
    public void debtorAgentTest() {
        // TODO: test debtorAgent
    }

    /**
     * Test the property 'merchantDetails'
     */
    @Test
    public void merchantDetailsTest() {
        // TODO: test merchantDetails
    }

    /**
     * Test the property 'proprietaryBankTransactionCode'
     */
    @Test
    public void proprietaryBankTransactionCodeTest() {
        // TODO: test proprietaryBankTransactionCode
    }

    /**
     * Test the property 'statementReference'
     */
    @Test
    public void statementReferenceTest() {
        // TODO: test statementReference
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'supplementaryData'
     */
    @Test
    public void supplementaryDataTest() {
        // TODO: test supplementaryData
    }

    /**
     * Test the property 'transactionId'
     */
    @Test
    public void transactionIdTest() {
        // TODO: test transactionId
    }

    /**
     * Test the property 'transactionInformation'
     */
    @Test
    public void transactionInformationTest() {
        // TODO: test transactionInformation
    }

    /**
     * Test the property 'transactionMutability'
     */
    @Test
    public void transactionMutabilityTest() {
        // TODO: test transactionMutability
    }

    /**
     * Test the property 'transactionReference'
     */
    @Test
    public void transactionReferenceTest() {
        // TODO: test transactionReference
    }

    /**
     * Test the property 'valueDateTime'
     */
    @Test
    public void valueDateTimeTest() {
        // TODO: test valueDateTime
    }

}
