/*
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * The version of the OpenAPI document: 3.1.7
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.OBBalanceType1Code;
import com.konfigthis.client.model.OBCreditDebitCode2;
import com.konfigthis.client.model.OBTransactionCashBalanceAmount;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OBTransactionCashBalance
 */
public class OBTransactionCashBalanceTest {
    private final OBTransactionCashBalance model = new OBTransactionCashBalance();

    /**
     * Model tests for OBTransactionCashBalance
     */
    @Test
    public void testOBTransactionCashBalance() {
        // TODO: test OBTransactionCashBalance
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'creditDebitIndicator'
     */
    @Test
    public void creditDebitIndicatorTest() {
        // TODO: test creditDebitIndicator
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

}
