/*
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * The version of the OpenAPI document: 3.1.7
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.OtherFeeTypePropertyInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OverdraftFeeChargeCapProperty
 */
public class OverdraftFeeChargeCapPropertyTest {
    private final OverdraftFeeChargeCapProperty model = new OverdraftFeeChargeCapProperty();

    /**
     * Model tests for OverdraftFeeChargeCapProperty
     */
    @Test
    public void testOverdraftFeeChargeCapProperty() {
        // TODO: test OverdraftFeeChargeCapProperty
    }

    /**
     * Test the property 'cappingPeriod'
     */
    @Test
    public void cappingPeriodTest() {
        // TODO: test cappingPeriod
    }

    /**
     * Test the property 'feeCapAmount'
     */
    @Test
    public void feeCapAmountTest() {
        // TODO: test feeCapAmount
    }

    /**
     * Test the property 'feeCapOccurrence'
     */
    @Test
    public void feeCapOccurrenceTest() {
        // TODO: test feeCapOccurrence
    }

    /**
     * Test the property 'feeType'
     */
    @Test
    public void feeTypeTest() {
        // TODO: test feeType
    }

    /**
     * Test the property 'minMaxType'
     */
    @Test
    public void minMaxTypeTest() {
        // TODO: test minMaxType
    }

    /**
     * Test the property 'notes'
     */
    @Test
    public void notesTest() {
        // TODO: test notes
    }

    /**
     * Test the property 'otherFeeType'
     */
    @Test
    public void otherFeeTypeTest() {
        // TODO: test otherFeeType
    }

    /**
     * Test the property 'overdraftControlIndicator'
     */
    @Test
    public void overdraftControlIndicatorTest() {
        // TODO: test overdraftControlIndicator
    }

}
