/*
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * The version of the OpenAPI document: 3.1.7
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.OverdraftFeeChargeCapPropertyInner;
import com.konfigthis.client.model.OverdraftFeeChargeDetailPropertyInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OverdraftFeesChargesPropertyInner1
 */
public class OverdraftFeesChargesPropertyInner1Test {
    private final OverdraftFeesChargesPropertyInner1 model = new OverdraftFeesChargesPropertyInner1();

    /**
     * Model tests for OverdraftFeesChargesPropertyInner1
     */
    @Test
    public void testOverdraftFeesChargesPropertyInner1() {
        // TODO: test OverdraftFeesChargesPropertyInner1
    }

    /**
     * Test the property 'overdraftFeeChargeCap'
     */
    @Test
    public void overdraftFeeChargeCapTest() {
        // TODO: test overdraftFeeChargeCap
    }

    /**
     * Test the property 'overdraftFeeChargeDetail'
     */
    @Test
    public void overdraftFeeChargeDetailTest() {
        // TODO: test overdraftFeeChargeDetail
    }

}
