/*
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * The version of the OpenAPI document: 3.1.7
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.OtherApplicationFrequencyProperty;
import com.konfigthis.client.model.OtherBankInterestTypeProperty;
import com.konfigthis.client.model.OtherCalculationFrequencyProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TierBandPropertyInner
 */
public class TierBandPropertyInnerTest {
    private final TierBandPropertyInner model = new TierBandPropertyInner();

    /**
     * Model tests for TierBandPropertyInner
     */
    @Test
    public void testTierBandPropertyInner() {
        // TODO: test TierBandPropertyInner
    }

    /**
     * Test the property 'AER'
     */
    @Test
    public void AERTest() {
        // TODO: test AER
    }

    /**
     * Test the property 'applicationFrequency'
     */
    @Test
    public void applicationFrequencyTest() {
        // TODO: test applicationFrequency
    }

    /**
     * Test the property 'bankInterestRate'
     */
    @Test
    public void bankInterestRateTest() {
        // TODO: test bankInterestRate
    }

    /**
     * Test the property 'bankInterestRateType'
     */
    @Test
    public void bankInterestRateTypeTest() {
        // TODO: test bankInterestRateType
    }

    /**
     * Test the property 'calculationFrequency'
     */
    @Test
    public void calculationFrequencyTest() {
        // TODO: test calculationFrequency
    }

    /**
     * Test the property 'depositInterestAppliedCoverage'
     */
    @Test
    public void depositInterestAppliedCoverageTest() {
        // TODO: test depositInterestAppliedCoverage
    }

    /**
     * Test the property 'fixedVariableInterestRateType'
     */
    @Test
    public void fixedVariableInterestRateTypeTest() {
        // TODO: test fixedVariableInterestRateType
    }

    /**
     * Test the property 'identification'
     */
    @Test
    public void identificationTest() {
        // TODO: test identification
    }

    /**
     * Test the property 'notes'
     */
    @Test
    public void notesTest() {
        // TODO: test notes
    }

    /**
     * Test the property 'otherApplicationFrequency'
     */
    @Test
    public void otherApplicationFrequencyTest() {
        // TODO: test otherApplicationFrequency
    }

    /**
     * Test the property 'otherBankInterestType'
     */
    @Test
    public void otherBankInterestTypeTest() {
        // TODO: test otherBankInterestType
    }

    /**
     * Test the property 'otherCalculationFrequency'
     */
    @Test
    public void otherCalculationFrequencyTest() {
        // TODO: test otherCalculationFrequency
    }

    /**
     * Test the property 'tierValueMaximum'
     */
    @Test
    public void tierValueMaximumTest() {
        // TODO: test tierValueMaximum
    }

    /**
     * Test the property 'tierValueMinimum'
     */
    @Test
    public void tierValueMinimumTest() {
        // TODO: test tierValueMinimum
    }

}
