/*
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * The version of the OpenAPI document: 3.1.7
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.FeeApplicableRangeProperty;
import com.konfigthis.client.model.FeeChargeCapPropertyInner;
import com.konfigthis.client.model.OtherApplicationFrequencyProperty1;
import com.konfigthis.client.model.OtherCalculationFrequencyProperty1;
import com.konfigthis.client.model.OtherFeeCategoryTypeProperty;
import com.konfigthis.client.model.OtherFeeRateTypeProperty;
import com.konfigthis.client.model.OtherFeeTypeProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * Other fees/charges details
 */
@ApiModel(description = "Other fees/charges details")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class FeeChargeDetailPropertyInner {
  /**
   * How frequently the fee/charge is applied to the account
   */
  @JsonAdapter(ApplicationFrequencyEnum.Adapter.class)
 public enum ApplicationFrequencyEnum {
    ONCLOSING("OnClosing"),
    
    ONOPENING("OnOpening"),
    
    CHARGINGPERIOD("ChargingPeriod"),
    
    DAILY("Daily"),
    
    PERITEM("PerItem"),
    
    MONTHLY("Monthly"),
    
    ONANNIVERSARY("OnAnniversary"),
    
    OTHER("Other"),
    
    PERHUNDREDPOUNDS("PerHundredPounds"),
    
    PERHOUR("PerHour"),
    
    PEROCCURRENCE("PerOccurrence"),
    
    PERSHEET("PerSheet"),
    
    PERTRANSACTION("PerTransaction"),
    
    PERTRANSACTIONAMOUNT("PerTransactionAmount"),
    
    PERTRANSACTIONPERCENTAGE("PerTransactionPercentage"),
    
    QUARTERLY("Quarterly"),
    
    SIXMONTHLY("SixMonthly"),
    
    STATEMENTMONTHLY("StatementMonthly"),
    
    WEEKLY("Weekly"),
    
    YEARLY("Yearly");

    private String value;

    ApplicationFrequencyEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ApplicationFrequencyEnum fromValue(String value) {
      for (ApplicationFrequencyEnum b : ApplicationFrequencyEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ApplicationFrequencyEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ApplicationFrequencyEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ApplicationFrequencyEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ApplicationFrequencyEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_APPLICATION_FREQUENCY = "ApplicationFrequency";
  @SerializedName(SERIALIZED_NAME_APPLICATION_FREQUENCY)
  private ApplicationFrequencyEnum applicationFrequency;

  /**
   * How frequently the fee/charge is calculated
   */
  @JsonAdapter(CalculationFrequencyEnum.Adapter.class)
 public enum CalculationFrequencyEnum {
    ONCLOSING("OnClosing"),
    
    ONOPENING("OnOpening"),
    
    CHARGINGPERIOD("ChargingPeriod"),
    
    DAILY("Daily"),
    
    PERITEM("PerItem"),
    
    MONTHLY("Monthly"),
    
    ONANNIVERSARY("OnAnniversary"),
    
    OTHER("Other"),
    
    PERHUNDREDPOUNDS("PerHundredPounds"),
    
    PERHOUR("PerHour"),
    
    PEROCCURRENCE("PerOccurrence"),
    
    PERSHEET("PerSheet"),
    
    PERTRANSACTION("PerTransaction"),
    
    PERTRANSACTIONAMOUNT("PerTransactionAmount"),
    
    PERTRANSACTIONPERCENTAGE("PerTransactionPercentage"),
    
    QUARTERLY("Quarterly"),
    
    SIXMONTHLY("SixMonthly"),
    
    STATEMENTMONTHLY("StatementMonthly"),
    
    WEEKLY("Weekly"),
    
    YEARLY("Yearly");

    private String value;

    CalculationFrequencyEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static CalculationFrequencyEnum fromValue(String value) {
      for (CalculationFrequencyEnum b : CalculationFrequencyEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<CalculationFrequencyEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final CalculationFrequencyEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public CalculationFrequencyEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return CalculationFrequencyEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_CALCULATION_FREQUENCY = "CalculationFrequency";
  @SerializedName(SERIALIZED_NAME_CALCULATION_FREQUENCY)
  private CalculationFrequencyEnum calculationFrequency;

  public static final String SERIALIZED_NAME_FEE_AMOUNT = "FeeAmount";
  @SerializedName(SERIALIZED_NAME_FEE_AMOUNT)
  private String feeAmount;

  public static final String SERIALIZED_NAME_FEE_APPLICABLE_RANGE = "FeeApplicableRange";
  @SerializedName(SERIALIZED_NAME_FEE_APPLICABLE_RANGE)
  private FeeApplicableRangeProperty feeApplicableRange;

  /**
   * Categorisation of fees and charges into standard categories.
   */
  @JsonAdapter(FeeCategoryEnum.Adapter.class)
 public enum FeeCategoryEnum {
    OTHER("Other"),
    
    SERVICING("Servicing");

    private String value;

    FeeCategoryEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static FeeCategoryEnum fromValue(String value) {
      for (FeeCategoryEnum b : FeeCategoryEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<FeeCategoryEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final FeeCategoryEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public FeeCategoryEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return FeeCategoryEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_FEE_CATEGORY = "FeeCategory";
  @SerializedName(SERIALIZED_NAME_FEE_CATEGORY)
  private FeeCategoryEnum feeCategory;

  public static final String SERIALIZED_NAME_FEE_CHARGE_CAP = "FeeChargeCap";
  @SerializedName(SERIALIZED_NAME_FEE_CHARGE_CAP)
  private List<FeeChargeCapPropertyInner> feeChargeCap = null;

  public static final String SERIALIZED_NAME_FEE_RATE = "FeeRate";
  @SerializedName(SERIALIZED_NAME_FEE_RATE)
  private String feeRate;

  /**
   * Rate type for Fee/Charge (where it is charged in terms of a rate rather than an amount)
   */
  @JsonAdapter(FeeRateTypeEnum.Adapter.class)
 public enum FeeRateTypeEnum {
    GROSS("Gross"),
    
    OTHER("Other");

    private String value;

    FeeRateTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static FeeRateTypeEnum fromValue(String value) {
      for (FeeRateTypeEnum b : FeeRateTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<FeeRateTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final FeeRateTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public FeeRateTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return FeeRateTypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_FEE_RATE_TYPE = "FeeRateType";
  @SerializedName(SERIALIZED_NAME_FEE_RATE_TYPE)
  private FeeRateTypeEnum feeRateType;

  /**
   * Fee/Charge Type
   */
  @JsonAdapter(FeeTypeEnum.Adapter.class)
 public enum FeeTypeEnum {
    OTHER("Other"),
    
    SERVICECACCOUNTFEE("ServiceCAccountFee"),
    
    SERVICECACCOUNTFEEMONTHLY("ServiceCAccountFeeMonthly"),
    
    SERVICECACCOUNTFEEQUARTERLY("ServiceCAccountFeeQuarterly"),
    
    SERVICECFIXEDTARIFF("ServiceCFixedTariff"),
    
    SERVICECBUSIDEPACCBREAKAGE("ServiceCBusiDepAccBreakage"),
    
    SERVICECMINIMUMMONTHLYFEE("ServiceCMinimumMonthlyFee"),
    
    SERVICECOTHER("ServiceCOther");

    private String value;

    FeeTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static FeeTypeEnum fromValue(String value) {
      for (FeeTypeEnum b : FeeTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<FeeTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final FeeTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public FeeTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return FeeTypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_FEE_TYPE = "FeeType";
  @SerializedName(SERIALIZED_NAME_FEE_TYPE)
  private FeeTypeEnum feeType;

  public static final String SERIALIZED_NAME_NEGOTIABLE_INDICATOR = "NegotiableIndicator";
  @SerializedName(SERIALIZED_NAME_NEGOTIABLE_INDICATOR)
  private Boolean negotiableIndicator;

  public static final String SERIALIZED_NAME_NOTES = "Notes";
  @SerializedName(SERIALIZED_NAME_NOTES)
  private List<String> notes = null;

  public static final String SERIALIZED_NAME_OTHER_APPLICATION_FREQUENCY = "OtherApplicationFrequency";
  @SerializedName(SERIALIZED_NAME_OTHER_APPLICATION_FREQUENCY)
  private OtherApplicationFrequencyProperty1 otherApplicationFrequency;

  public static final String SERIALIZED_NAME_OTHER_CALCULATION_FREQUENCY = "OtherCalculationFrequency";
  @SerializedName(SERIALIZED_NAME_OTHER_CALCULATION_FREQUENCY)
  private OtherCalculationFrequencyProperty1 otherCalculationFrequency;

  public static final String SERIALIZED_NAME_OTHER_FEE_CATEGORY_TYPE = "OtherFeeCategoryType";
  @SerializedName(SERIALIZED_NAME_OTHER_FEE_CATEGORY_TYPE)
  private OtherFeeCategoryTypeProperty otherFeeCategoryType;

  public static final String SERIALIZED_NAME_OTHER_FEE_RATE_TYPE = "OtherFeeRateType";
  @SerializedName(SERIALIZED_NAME_OTHER_FEE_RATE_TYPE)
  private OtherFeeRateTypeProperty otherFeeRateType;

  public static final String SERIALIZED_NAME_OTHER_FEE_TYPE = "OtherFeeType";
  @SerializedName(SERIALIZED_NAME_OTHER_FEE_TYPE)
  private OtherFeeTypeProperty otherFeeType;

  public FeeChargeDetailPropertyInner() {
  }

  public FeeChargeDetailPropertyInner applicationFrequency(ApplicationFrequencyEnum applicationFrequency) {
    
    
    
    
    this.applicationFrequency = applicationFrequency;
    return this;
  }

   /**
   * How frequently the fee/charge is applied to the account
   * @return applicationFrequency
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "How frequently the fee/charge is applied to the account")

  public ApplicationFrequencyEnum getApplicationFrequency() {
    return applicationFrequency;
  }


  public void setApplicationFrequency(ApplicationFrequencyEnum applicationFrequency) {
    
    
    
    this.applicationFrequency = applicationFrequency;
  }


  public FeeChargeDetailPropertyInner calculationFrequency(CalculationFrequencyEnum calculationFrequency) {
    
    
    
    
    this.calculationFrequency = calculationFrequency;
    return this;
  }

   /**
   * How frequently the fee/charge is calculated
   * @return calculationFrequency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "How frequently the fee/charge is calculated")

  public CalculationFrequencyEnum getCalculationFrequency() {
    return calculationFrequency;
  }


  public void setCalculationFrequency(CalculationFrequencyEnum calculationFrequency) {
    
    
    
    this.calculationFrequency = calculationFrequency;
  }


  public FeeChargeDetailPropertyInner feeAmount(String feeAmount) {
    
    
    
    
    this.feeAmount = feeAmount;
    return this;
  }

   /**
   * Fee Amount charged for a fee/charge (where it is charged in terms of an amount rather than a rate)
   * @return feeAmount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Fee Amount charged for a fee/charge (where it is charged in terms of an amount rather than a rate)")

  public String getFeeAmount() {
    return feeAmount;
  }


  public void setFeeAmount(String feeAmount) {
    
    
    
    this.feeAmount = feeAmount;
  }


  public FeeChargeDetailPropertyInner feeApplicableRange(FeeApplicableRangeProperty feeApplicableRange) {
    
    
    
    
    this.feeApplicableRange = feeApplicableRange;
    return this;
  }

   /**
   * Get feeApplicableRange
   * @return feeApplicableRange
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public FeeApplicableRangeProperty getFeeApplicableRange() {
    return feeApplicableRange;
  }


  public void setFeeApplicableRange(FeeApplicableRangeProperty feeApplicableRange) {
    
    
    
    this.feeApplicableRange = feeApplicableRange;
  }


  public FeeChargeDetailPropertyInner feeCategory(FeeCategoryEnum feeCategory) {
    
    
    
    
    this.feeCategory = feeCategory;
    return this;
  }

   /**
   * Categorisation of fees and charges into standard categories.
   * @return feeCategory
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Categorisation of fees and charges into standard categories.")

  public FeeCategoryEnum getFeeCategory() {
    return feeCategory;
  }


  public void setFeeCategory(FeeCategoryEnum feeCategory) {
    
    
    
    this.feeCategory = feeCategory;
  }


  public FeeChargeDetailPropertyInner feeChargeCap(List<FeeChargeCapPropertyInner> feeChargeCap) {
    
    
    
    
    this.feeChargeCap = feeChargeCap;
    return this;
  }

  public FeeChargeDetailPropertyInner addFeeChargeCapItem(FeeChargeCapPropertyInner feeChargeCapItem) {
    if (this.feeChargeCap == null) {
      this.feeChargeCap = new ArrayList<>();
    }
    this.feeChargeCap.add(feeChargeCapItem);
    return this;
  }

   /**
   * Details about any caps (maximum charges) that apply to a particular or group of fee/charge
   * @return feeChargeCap
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Details about any caps (maximum charges) that apply to a particular or group of fee/charge")

  public List<FeeChargeCapPropertyInner> getFeeChargeCap() {
    return feeChargeCap;
  }


  public void setFeeChargeCap(List<FeeChargeCapPropertyInner> feeChargeCap) {
    
    
    
    this.feeChargeCap = feeChargeCap;
  }


  public FeeChargeDetailPropertyInner feeRate(String feeRate) {
    
    
    
    
    this.feeRate = feeRate;
    return this;
  }

   /**
   * Rate charged for Fee/Charge (where it is charged in terms of a rate rather than an amount)
   * @return feeRate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Rate charged for Fee/Charge (where it is charged in terms of a rate rather than an amount)")

  public String getFeeRate() {
    return feeRate;
  }


  public void setFeeRate(String feeRate) {
    
    
    
    this.feeRate = feeRate;
  }


  public FeeChargeDetailPropertyInner feeRateType(FeeRateTypeEnum feeRateType) {
    
    
    
    
    this.feeRateType = feeRateType;
    return this;
  }

   /**
   * Rate type for Fee/Charge (where it is charged in terms of a rate rather than an amount)
   * @return feeRateType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Rate type for Fee/Charge (where it is charged in terms of a rate rather than an amount)")

  public FeeRateTypeEnum getFeeRateType() {
    return feeRateType;
  }


  public void setFeeRateType(FeeRateTypeEnum feeRateType) {
    
    
    
    this.feeRateType = feeRateType;
  }


  public FeeChargeDetailPropertyInner feeType(FeeTypeEnum feeType) {
    
    
    
    
    this.feeType = feeType;
    return this;
  }

   /**
   * Fee/Charge Type
   * @return feeType
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Fee/Charge Type")

  public FeeTypeEnum getFeeType() {
    return feeType;
  }


  public void setFeeType(FeeTypeEnum feeType) {
    
    
    
    this.feeType = feeType;
  }


  public FeeChargeDetailPropertyInner negotiableIndicator(Boolean negotiableIndicator) {
    
    
    
    
    this.negotiableIndicator = negotiableIndicator;
    return this;
  }

   /**
   * Fee/charge which is usually negotiable rather than a fixed amount
   * @return negotiableIndicator
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Fee/charge which is usually negotiable rather than a fixed amount")

  public Boolean getNegotiableIndicator() {
    return negotiableIndicator;
  }


  public void setNegotiableIndicator(Boolean negotiableIndicator) {
    
    
    
    this.negotiableIndicator = negotiableIndicator;
  }


  public FeeChargeDetailPropertyInner notes(List<String> notes) {
    
    
    
    
    this.notes = notes;
    return this;
  }

  public FeeChargeDetailPropertyInner addNotesItem(String notesItem) {
    if (this.notes == null) {
      this.notes = new ArrayList<>();
    }
    this.notes.add(notesItem);
    return this;
  }

   /**
   * Optional additional notes to supplement the fee/charge details.
   * @return notes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Optional additional notes to supplement the fee/charge details.")

  public List<String> getNotes() {
    return notes;
  }


  public void setNotes(List<String> notes) {
    
    
    
    this.notes = notes;
  }


  public FeeChargeDetailPropertyInner otherApplicationFrequency(OtherApplicationFrequencyProperty1 otherApplicationFrequency) {
    
    
    
    
    this.otherApplicationFrequency = otherApplicationFrequency;
    return this;
  }

   /**
   * Get otherApplicationFrequency
   * @return otherApplicationFrequency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OtherApplicationFrequencyProperty1 getOtherApplicationFrequency() {
    return otherApplicationFrequency;
  }


  public void setOtherApplicationFrequency(OtherApplicationFrequencyProperty1 otherApplicationFrequency) {
    
    
    
    this.otherApplicationFrequency = otherApplicationFrequency;
  }


  public FeeChargeDetailPropertyInner otherCalculationFrequency(OtherCalculationFrequencyProperty1 otherCalculationFrequency) {
    
    
    
    
    this.otherCalculationFrequency = otherCalculationFrequency;
    return this;
  }

   /**
   * Get otherCalculationFrequency
   * @return otherCalculationFrequency
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OtherCalculationFrequencyProperty1 getOtherCalculationFrequency() {
    return otherCalculationFrequency;
  }


  public void setOtherCalculationFrequency(OtherCalculationFrequencyProperty1 otherCalculationFrequency) {
    
    
    
    this.otherCalculationFrequency = otherCalculationFrequency;
  }


  public FeeChargeDetailPropertyInner otherFeeCategoryType(OtherFeeCategoryTypeProperty otherFeeCategoryType) {
    
    
    
    
    this.otherFeeCategoryType = otherFeeCategoryType;
    return this;
  }

   /**
   * Get otherFeeCategoryType
   * @return otherFeeCategoryType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OtherFeeCategoryTypeProperty getOtherFeeCategoryType() {
    return otherFeeCategoryType;
  }


  public void setOtherFeeCategoryType(OtherFeeCategoryTypeProperty otherFeeCategoryType) {
    
    
    
    this.otherFeeCategoryType = otherFeeCategoryType;
  }


  public FeeChargeDetailPropertyInner otherFeeRateType(OtherFeeRateTypeProperty otherFeeRateType) {
    
    
    
    
    this.otherFeeRateType = otherFeeRateType;
    return this;
  }

   /**
   * Get otherFeeRateType
   * @return otherFeeRateType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OtherFeeRateTypeProperty getOtherFeeRateType() {
    return otherFeeRateType;
  }


  public void setOtherFeeRateType(OtherFeeRateTypeProperty otherFeeRateType) {
    
    
    
    this.otherFeeRateType = otherFeeRateType;
  }


  public FeeChargeDetailPropertyInner otherFeeType(OtherFeeTypeProperty otherFeeType) {
    
    
    
    
    this.otherFeeType = otherFeeType;
    return this;
  }

   /**
   * Get otherFeeType
   * @return otherFeeType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OtherFeeTypeProperty getOtherFeeType() {
    return otherFeeType;
  }


  public void setOtherFeeType(OtherFeeTypeProperty otherFeeType) {
    
    
    
    this.otherFeeType = otherFeeType;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the FeeChargeDetailPropertyInner instance itself
   */
  public FeeChargeDetailPropertyInner putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FeeChargeDetailPropertyInner feeChargeDetailPropertyInner = (FeeChargeDetailPropertyInner) o;
    return Objects.equals(this.applicationFrequency, feeChargeDetailPropertyInner.applicationFrequency) &&
        Objects.equals(this.calculationFrequency, feeChargeDetailPropertyInner.calculationFrequency) &&
        Objects.equals(this.feeAmount, feeChargeDetailPropertyInner.feeAmount) &&
        Objects.equals(this.feeApplicableRange, feeChargeDetailPropertyInner.feeApplicableRange) &&
        Objects.equals(this.feeCategory, feeChargeDetailPropertyInner.feeCategory) &&
        Objects.equals(this.feeChargeCap, feeChargeDetailPropertyInner.feeChargeCap) &&
        Objects.equals(this.feeRate, feeChargeDetailPropertyInner.feeRate) &&
        Objects.equals(this.feeRateType, feeChargeDetailPropertyInner.feeRateType) &&
        Objects.equals(this.feeType, feeChargeDetailPropertyInner.feeType) &&
        Objects.equals(this.negotiableIndicator, feeChargeDetailPropertyInner.negotiableIndicator) &&
        Objects.equals(this.notes, feeChargeDetailPropertyInner.notes) &&
        Objects.equals(this.otherApplicationFrequency, feeChargeDetailPropertyInner.otherApplicationFrequency) &&
        Objects.equals(this.otherCalculationFrequency, feeChargeDetailPropertyInner.otherCalculationFrequency) &&
        Objects.equals(this.otherFeeCategoryType, feeChargeDetailPropertyInner.otherFeeCategoryType) &&
        Objects.equals(this.otherFeeRateType, feeChargeDetailPropertyInner.otherFeeRateType) &&
        Objects.equals(this.otherFeeType, feeChargeDetailPropertyInner.otherFeeType)&&
        Objects.equals(this.additionalProperties, feeChargeDetailPropertyInner.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(applicationFrequency, calculationFrequency, feeAmount, feeApplicableRange, feeCategory, feeChargeCap, feeRate, feeRateType, feeType, negotiableIndicator, notes, otherApplicationFrequency, otherCalculationFrequency, otherFeeCategoryType, otherFeeRateType, otherFeeType, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FeeChargeDetailPropertyInner {\n");
    sb.append("    applicationFrequency: ").append(toIndentedString(applicationFrequency)).append("\n");
    sb.append("    calculationFrequency: ").append(toIndentedString(calculationFrequency)).append("\n");
    sb.append("    feeAmount: ").append(toIndentedString(feeAmount)).append("\n");
    sb.append("    feeApplicableRange: ").append(toIndentedString(feeApplicableRange)).append("\n");
    sb.append("    feeCategory: ").append(toIndentedString(feeCategory)).append("\n");
    sb.append("    feeChargeCap: ").append(toIndentedString(feeChargeCap)).append("\n");
    sb.append("    feeRate: ").append(toIndentedString(feeRate)).append("\n");
    sb.append("    feeRateType: ").append(toIndentedString(feeRateType)).append("\n");
    sb.append("    feeType: ").append(toIndentedString(feeType)).append("\n");
    sb.append("    negotiableIndicator: ").append(toIndentedString(negotiableIndicator)).append("\n");
    sb.append("    notes: ").append(toIndentedString(notes)).append("\n");
    sb.append("    otherApplicationFrequency: ").append(toIndentedString(otherApplicationFrequency)).append("\n");
    sb.append("    otherCalculationFrequency: ").append(toIndentedString(otherCalculationFrequency)).append("\n");
    sb.append("    otherFeeCategoryType: ").append(toIndentedString(otherFeeCategoryType)).append("\n");
    sb.append("    otherFeeRateType: ").append(toIndentedString(otherFeeRateType)).append("\n");
    sb.append("    otherFeeType: ").append(toIndentedString(otherFeeType)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("ApplicationFrequency");
    openapiFields.add("CalculationFrequency");
    openapiFields.add("FeeAmount");
    openapiFields.add("FeeApplicableRange");
    openapiFields.add("FeeCategory");
    openapiFields.add("FeeChargeCap");
    openapiFields.add("FeeRate");
    openapiFields.add("FeeRateType");
    openapiFields.add("FeeType");
    openapiFields.add("NegotiableIndicator");
    openapiFields.add("Notes");
    openapiFields.add("OtherApplicationFrequency");
    openapiFields.add("OtherCalculationFrequency");
    openapiFields.add("OtherFeeCategoryType");
    openapiFields.add("OtherFeeRateType");
    openapiFields.add("OtherFeeType");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("ApplicationFrequency");
    openapiRequiredFields.add("FeeCategory");
    openapiRequiredFields.add("FeeType");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to FeeChargeDetailPropertyInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!FeeChargeDetailPropertyInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in FeeChargeDetailPropertyInner is not found in the empty JSON string", FeeChargeDetailPropertyInner.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : FeeChargeDetailPropertyInner.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("ApplicationFrequency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ApplicationFrequency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ApplicationFrequency").toString()));
      }
      if ((jsonObj.get("CalculationFrequency") != null && !jsonObj.get("CalculationFrequency").isJsonNull()) && !jsonObj.get("CalculationFrequency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `CalculationFrequency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("CalculationFrequency").toString()));
      }
      if ((jsonObj.get("FeeAmount") != null && !jsonObj.get("FeeAmount").isJsonNull()) && !jsonObj.get("FeeAmount").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `FeeAmount` to be a primitive type in the JSON string but got `%s`", jsonObj.get("FeeAmount").toString()));
      }
      // validate the optional field `FeeApplicableRange`
      if (jsonObj.get("FeeApplicableRange") != null && !jsonObj.get("FeeApplicableRange").isJsonNull()) {
        FeeApplicableRangeProperty.validateJsonObject(jsonObj.getAsJsonObject("FeeApplicableRange"));
      }
      if (!jsonObj.get("FeeCategory").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `FeeCategory` to be a primitive type in the JSON string but got `%s`", jsonObj.get("FeeCategory").toString()));
      }
      if (jsonObj.get("FeeChargeCap") != null && !jsonObj.get("FeeChargeCap").isJsonNull()) {
        JsonArray jsonArrayfeeChargeCap = jsonObj.getAsJsonArray("FeeChargeCap");
        if (jsonArrayfeeChargeCap != null) {
          // ensure the json data is an array
          if (!jsonObj.get("FeeChargeCap").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `FeeChargeCap` to be an array in the JSON string but got `%s`", jsonObj.get("FeeChargeCap").toString()));
          }

          // validate the optional field `FeeChargeCap` (array)
          for (int i = 0; i < jsonArrayfeeChargeCap.size(); i++) {
            FeeChargeCapPropertyInner.validateJsonObject(jsonArrayfeeChargeCap.get(i).getAsJsonObject());
          };
        }
      }
      if ((jsonObj.get("FeeRate") != null && !jsonObj.get("FeeRate").isJsonNull()) && !jsonObj.get("FeeRate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `FeeRate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("FeeRate").toString()));
      }
      if ((jsonObj.get("FeeRateType") != null && !jsonObj.get("FeeRateType").isJsonNull()) && !jsonObj.get("FeeRateType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `FeeRateType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("FeeRateType").toString()));
      }
      if (!jsonObj.get("FeeType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `FeeType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("FeeType").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("Notes") != null && !jsonObj.get("Notes").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `Notes` to be an array in the JSON string but got `%s`", jsonObj.get("Notes").toString()));
      }
      // validate the optional field `OtherApplicationFrequency`
      if (jsonObj.get("OtherApplicationFrequency") != null && !jsonObj.get("OtherApplicationFrequency").isJsonNull()) {
        OtherApplicationFrequencyProperty1.validateJsonObject(jsonObj.getAsJsonObject("OtherApplicationFrequency"));
      }
      // validate the optional field `OtherCalculationFrequency`
      if (jsonObj.get("OtherCalculationFrequency") != null && !jsonObj.get("OtherCalculationFrequency").isJsonNull()) {
        OtherCalculationFrequencyProperty1.validateJsonObject(jsonObj.getAsJsonObject("OtherCalculationFrequency"));
      }
      // validate the optional field `OtherFeeCategoryType`
      if (jsonObj.get("OtherFeeCategoryType") != null && !jsonObj.get("OtherFeeCategoryType").isJsonNull()) {
        OtherFeeCategoryTypeProperty.validateJsonObject(jsonObj.getAsJsonObject("OtherFeeCategoryType"));
      }
      // validate the optional field `OtherFeeRateType`
      if (jsonObj.get("OtherFeeRateType") != null && !jsonObj.get("OtherFeeRateType").isJsonNull()) {
        OtherFeeRateTypeProperty.validateJsonObject(jsonObj.getAsJsonObject("OtherFeeRateType"));
      }
      // validate the optional field `OtherFeeType`
      if (jsonObj.get("OtherFeeType") != null && !jsonObj.get("OtherFeeType").isJsonNull()) {
        OtherFeeTypeProperty.validateJsonObject(jsonObj.getAsJsonObject("OtherFeeType"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FeeChargeDetailPropertyInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FeeChargeDetailPropertyInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FeeChargeDetailPropertyInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FeeChargeDetailPropertyInner.class));

       return (TypeAdapter<T>) new TypeAdapter<FeeChargeDetailPropertyInner>() {
           @Override
           public void write(JsonWriter out, FeeChargeDetailPropertyInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public FeeChargeDetailPropertyInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             FeeChargeDetailPropertyInner instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of FeeChargeDetailPropertyInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of FeeChargeDetailPropertyInner
  * @throws IOException if the JSON string is invalid with respect to FeeChargeDetailPropertyInner
  */
  public static FeeChargeDetailPropertyInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FeeChargeDetailPropertyInner.class);
  }

 /**
  * Convert an instance of FeeChargeDetailPropertyInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

