/*
 * Account and Transaction API Specification
 * Swagger for Account and Transaction API Specification
 *
 * The version of the OpenAPI document: 3.1.7
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Statement type, in a coded form.
 */
@JsonAdapter(OBExternalStatementType1Code.Adapter.class)public enum OBExternalStatementType1Code {
  
  ACCOUNTCLOSURE("AccountClosure"),
  
  ACCOUNTOPENING("AccountOpening"),
  
  ANNUAL("Annual"),
  
  INTERIM("Interim"),
  
  REGULARPERIODIC("RegularPeriodic");

  private String value;

  OBExternalStatementType1Code(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static OBExternalStatementType1Code fromValue(String value) {
    for (OBExternalStatementType1Code b : OBExternalStatementType1Code.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<OBExternalStatementType1Code> {
    @Override
    public void write(final JsonWriter jsonWriter, final OBExternalStatementType1Code enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public OBExternalStatementType1Code read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return OBExternalStatementType1Code.fromValue(value);
    }
  }
}

